kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hello-app
spec:
  rules:
  - http:
      paths:
      - path: /v1
        backend:
          serviceName: hello-app-v1
          servicePort: 8080
      - path: /v2
        backend:
          serviceName: hello-app-v2
          servicePort: 8080